### PR TITLE
Modify Student Model to include FullName + Bug Fixes (backend seed files)

### LINKED ISSUE #33: Remove PK from seed files
In the seed files, we should not include the Primary Key in the seed data (e.g. `StudentID` etc.). Let the DB handle creating and inserting it.

### PR DESCRIPTION
**Pull request by xuanjane**
[IRRC-59]-https://bootcamp-irrc.atlassian.net/browse/IRRC-59: Modify Student Model to include FullName
[IRRC-65]-https://bootcamp-irrc.atlassian.net/browse/IRRC-65: Remove PK from seed files
Closes #33 
1. Modify Student Model to include FullName. Based on and follows from #29  
2. Remove PK from seedfiles 
3. UPPERCASE status & language seeds

### CODE REVIEW

**Review by thchia — APPROVED** [review]
LGTM

File: backend/migrations/20201107133524_add_fullname_to_students.js [hunk 1]
```diff
@@ -0,0 +1,15 @@
+const { tableStudents } = require('../src/models/student')
+
+exports.up = function(knex, Promise) {
+    return knex.schema.table(tableStudents, (table) => {
+        table.text('FullName').notNullable().defaultTo('fullname');
```
Comment (lauratsui) [inline backend/migrations/20201107133524_add_fullname_to_students.js]: Maybe can remove .defaultTo('fullname'), so that if someone forgets to key in a full name, the database returns an error so the person is forced to key in something. Might be difficult if the database keeps getting a series of "fullname"s

**Review by lauratsui — CHANGES_REQUESTED** [review]
Just one comment on the first file line 5

File: backend/migrations/20201107133524_add_fullname_to_students.js (hunk 1 above)
Comment (xuanjane) [reply backend/migrations/20201107133524_add_fullname_to_students.js]: Hi Laura, yes, we have changed the defaultTo to an empty string instead. We kept the defaultTo to prevent the migration rollback errors if we were to change the table schema. Hope that works for you :)

Comment (thchia) [reply backend/migrations/20201107133524_add_fullname_to_students.js]: @xuanjane makes sense. @lauratsui you can update your approval status to Approved.

**Review by nondescryptid — CHANGES_REQUESTED** [review]
should the properties in students.js (in "models") be updated? Can replace FirstName and LastName with FullName under "properties" (l.59 and 60)  and "required" (l.55). This feedback is based on trying it out with Postman — I wasn't able to POST new students to the backend until the above changes were made. 

Do we still need line 13-15? Since we have FullName, it seems like that function is no longer needed. I'm not very familiar with backend though, so I'd like to check if there's a reason for us to keep it

**Comment by xuanjane** [comment]
> should the properties in students.js (in "models") be updated? Can replace FirstName and LastName with FullName under "properties" (l.59 and 60) and "required" (l.55). This feedback is based on trying it out with Postman — I wasn't able to POST new students to the backend until the above changes were made.
> 
> Do we still need line 13-15? Since we have FullName, it seems like that function is no longer needed. I'm not very familiar with backend though, so I'd like to check if there's a reason for us to keep it

Hey @Tomoe, good point! Thank you and have edited 👍

**Review by nondescryptid — APPROVED** [review]
LGTM :)
